searchSpaceFile: search_space.json
trialCommand: python3 main.py
trialGpuNumber: 1
trialConcurrency: 1
tuner:
  name: TPE
  classArgs:
    optimize_mode: minimize
trainingService:
  platform: local
  useActiveGpu: false
